src/Entity/Commande.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CommandeRepository")
 */
class Commande
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $montant;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_enregistrement;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $etat;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Membre", inversedBy="commandes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $membre;

     /**
     * @ORM\OneToMany(targetEntity="App\Entity\Details", mappedBy="commande", orphanRemoval=true, cascade={"persist"})
     */
    private $details;
    

    public function __construct()
    {
        $this->details = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMontant(): ?string
    {
        return $this->montant;
    }

    public function setMontant(string $montant): self
    {
        $this->montant = $montant;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): self
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }

    public function getEtat(): ?string
    {
        return $this->etat;
    }

    public function setEtat(string $etat): self
    {
        $this->etat = $etat;

        return $this;
    }

    public function getMembre(): ?Membre
    {
        return $this->membre;
    }

    public function setMembre(?Membre $membre): self
    {
        $this->membre = $membre;

        return $this;
    }

    /**
     * @return Collection|Details[]
     */
    public function getDetails(): Collection
    {
        return $this->details;
    }

    public function addDetail(Details $detail): self
    {
        if (!$this->details->contains($detail)) {
            $this->details[] = $detail;
            $detail->setCommande($this);
        }

        return $this;
    }

    public function removeDetail(Details $detail): self
    {
        if ($this->details->contains($detail)) {
            $this->details->removeElement($detail);
            // set the owning side to null (unless already changed)
            if ($detail->getCommande() === $this) {
                $detail->setCommande(null);
            }
        }

        return $this;
    }
}

src/Entity/Membre.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MembreRepository")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class Membre implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $pseudo;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=1)
     */
    private $civilite;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=5)
     */
    private $code_postal;

    /**
     * @ORM\Column(type="string", length=200)
     */
    private $adresse;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Commande", mappedBy="membre", orphanRemoval=true)
     */
    private $commandes;

    public function __construct()
    {
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getCivilite(): ?string
    {
        return $this->civilite;
    }

    public function setCivilite(string $civilite): self
    {
        $this->civilite = $civilite;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(string $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    /**
     * @return Collection|Commande[]
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes[] = $commande;
            $commande->setMembre($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->contains($commande)) {
            $this->commandes->removeElement($commande);
            // set the owning side to null (unless already changed)
            if ($commande->getMembre() === $this) {
                $commande->setMembre(null);
            }
        }

        return $this;
    }
}

src/Form/MembreType.php
<?php

namespace App\Form;

use App\Entity\Membre;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MembreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('email')
            // ->add('roles', TextType::class, ['mapped' => false])
            ->add('roles', ChoiceType::class, [
                'choices' => ['membre' => 'ROLE_USER',
                             'administrateur' => 'ROLE_ADMIN',
                             'super admin' => 'ROLE_SUPER_ADMIN'
                ],
                'required' => true,
                'multiple' => true,
                "label" => "Rôles"
            ])
            ->add('password', PasswordType::class, ['required' => false, 'mapped' => false])
            ->add('pseudo')
            ->add('nom')
            ->add('prenom')
            ->add('civilite')
            ->add('ville')
            ->add('code_postal')
            ->add('adresse')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Membre::class,
        ]);
    }
}

src/Controller/MembreController.php
<?php

namespace App\Controller;

use App\Entity\Membre;
use App\Form\MembreType;
use App\Form\ProfilType;
use App\Repository\MembreRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class MembreController extends AbstractController
{
    /**
     * @Route("/admin/membre", name="membre_index", methods={"GET"})
     */
    public function index(MembreRepository $membreRepository): Response
    {
        return $this->render('membre/index.html.twig', [
            'membres' => $membreRepository->findAll(),
        ]);
    }

    /**
     * @Route("/admin/membre/new", name="membre_new", methods={"GET"})
     */
    public function new(Request $request): Response
    {
        $membre = new Membre();
        $form = $this->createForm(MembreType::class, $membre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($membre);
            $entityManager->flush();

            return $this->redirectToRoute('membre_index');
        }

        return $this->render('membre/new.html.twig', [
            'membre' => $membre,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/admin/membre{id}", name="membre_show", methods={"GET"})
     */
    public function show(Membre $membre): Response
    {
        return $this->render('membre/show.html.twig', [
            'membre' => $membre,
        ]);
    }

    /**
     * @Route("/admin/membre{id}/edit", name="membre_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Membre $membre): Response
    {
        $form = $this->createForm(MembreType::class, $membre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $roles = $membre->getRoles();
            $membre->setRoles(array_values($roles));
            $this->getDoctrine()->getManager()->flush();
            return $this->redirectToRoute('membre_index');
        }

        return $this->render('membre/edit.html.twig', [
            'membre' => $membre,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/admin/membre{id}", name="membre_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Membre $membre): Response
    {
        if ($this->isCsrfTokenValid('delete'.$membre->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($membre);
            $entityManager->flush();
        }

        return $this->redirectToRoute('membre_index');
    }
       /**
     * @Route("/profil", name="profil", methods={"GET"})
     */
    public function profil(): Response
    {

        return $this->render('membre/profil.html.twig', []);
    }
    /**
    * @Route("/profil/modifier", name="profil_modifier", methods={"GET","POST"})
    */
    public function profil_modifier(Request $request, MembreRepository $membreRepository): Response
    {
        $membre = $this->getUser();
        $form = $this->createForm(ProfilType::class, $membre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if($mdp = $form->get('passwword')->getData()){
                $membre->setPassWord(password_hash($mdp,PASSWORD_DEFAULT));
            }else{
                $membre->setPassword($membreRepository->find($membre->getId()->getPassword()));
            }
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('membre_index');
        }

        return $this->render('membre/edit.html.twig', [
            'membre' => $membre,
            'form' => $form->createView(),
        ]);
    }

}

templates/membre/_delete_form.html.twig
<form method="post" action="{{ path('membre_delete', {'id': membre.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ membre.id) }}">
    <button class="btn">Delete</button>
</form>

templates/membre/_form.html.twig
{#
    {{form(form)}} # affiche le formulaire
{{ form_start(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}
    # affiche le bouton save puis le formulaire
#-----------------------------------------------
    {{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
    {{ form_end(form) }}
    # affiche tous les champs puis le formulaire
#-----------------------------------------------
    {{ form_start(form) }}
    {{ form_widget(form.email) }}
    {{ form_widget(form.nom) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
    {{ form_end(form) }}
    # affiche d'abord le champ email, ensuite nom, ensuite bouton  et enfin tous les autres champs
#-----------------------------------------------
    
#}

{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/membre/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Membre{% endblock %}


{% block title %}
    {% if is_granted('ROLE_ADMIN') %}
        Edit Membre
    {% else %}
        Modifier Le Profil
    {% endif %}
{% endblock %}

{% block body %}

<h1>{{ is_granted('ROLE_ADMIN') ? 'Modifier le membre' : 'Modifier le Profil' }}</h1>


    {{ include('membre/_form.html.twig', {'button_label': 'Update'}) }}

    {%if(is_granted('ROLES_ADMIN'))%}
    <a href="{{ path('membre_index') }}">back to list</a>
    {% endif %}

    {{ include('membre/_delete_form.html.twig') }}
{% endblock %}

templates/membre/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Membre index{% endblock %}

{% block body %}
    <h1>Membre index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Email</th>
                <th>Roles</th>
                <th>Password</th>
                <th>Pseudo</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Civilite</th>
                <th>Ville</th>
                <th>Code_postal</th>
                <th>Adresse</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for membre in membres %}
            <tr>
                <td>{{ membre.id }}</td>
                <td>{{ membre.email }}</td>
                <td>{{ membre.roles ? membre.roles|json_encode : '' }}</td>
                <td>{{ membre.password }}</td>
                <td>{{ membre.pseudo }}</td>
                <td>{{ membre.nom }}</td>
                <td>{{ membre.prenom }}</td>
                <td>{{ membre.civilite }}</td>
                <td>{{ membre.ville }}</td>
                <td>{{ membre.codePostal }}</td>
                <td>{{ membre.adresse }}</td>
                <td>
                    <a href="{{ path('membre_show', {'id': membre.id}) }}">show</a>
                    <a href="{{ path('membre_edit', {'id': membre.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="12">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('membre_new') }}">Create new</a>
{% endblock %}

templates/membre/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Membre{% endblock %}

{% block body %}
    <h1>Create new Membre</h1>

    {{ include('membre/_form.html.twig') }}

    <a href="{{ path('membre_index') }}">back to list</a>
{% endblock %}

templates/membre/profil.html.twig
{% extends 'base.html.twig' %}

{% block title %}app.user{% endblock %}

{% block body %}
    <h1>Mon profil</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Email</th>
                <td>{{ app.user.email }}</td>
            </tr>
            
            <tr>
                <th>Pseudo</th>
                <td>{{ app.user.pseudo }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ app.user.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ app.user.prenom }}</td>
            </tr>
            <tr>
                <th>Civilite</th>
                <td>{{ app.user.civilite }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ app.user.ville }}</td>
            </tr>
            <tr>
                <th>Code postal</th>
                <td>{{ app.user.codePostal }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ app.user.adresse }}</td>
            </tr>
        </tbody>
    </table>

    <div>
        <h2>Nombre <span>de commande(s) : {{ app.user.commandes |length }} </span></h2>
        <table class="table">
            <thead class="thead-dark">
                <th>Date</th>
                <th>Montant</th>
                <th>Etat</th>
                <th>Actions</th>
            </thead>
            {% for commande in app.user.commandes %}
                <tr>
                    <td>{{ commande.dateEnregistrement|date("d/m/Y") }}</td>
                    <td>{{ commande.montant }}</td>
                    <td>{{ commande.etat }}</td>
                    <td><a href="{{ path('commande_detail', {'id': commande.id}) }}"><i class="fa fa-book"></i></a></td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <a href="{{ path('profil_modifier') }}">Modifier</a>
{% endblock %}

templates/membre/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Membre{% endblock %}

{% block body %}
    <h1>Membre</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ membre.id }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ membre.email }}</td>
            </tr>
            <tr>
                <th>Roles</th>
                <td>{{ membre.roles ? membre.roles|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ membre.password }}</td>
            </tr>
            <tr>
                <th>Pseudo</th>
                <td>{{ membre.pseudo }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ membre.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ membre.prenom }}</td>
            </tr>
            <tr>
                <th>Civilite</th>
                <td>{{ membre.civilite }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ membre.ville }}</td>
            </tr>
            <tr>
                <th>Code_postal</th>
                <td>{{ membre.codePostal }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ membre.adresse }}</td>
            </tr>
        </tbody>
    </table>

    <div>
        <h2>Nombre <span>de commande(s) : {{ membre.commandes |length }} </span></h2>
        <table class="table">
            <thead class="thead-dark">
                <th>Date</th>
                <th>Montant</th>
                <th>Etat</th>
                <th>Actions</th>
            </thead>
            {% for commande in membre.commandes %}
                <tr>
                    <td>{{ commande.dateEnregistrement|date("d/m/Y") }}</td>
                    <td>{{ commande.montant }}</td>
                    <td>{{ commande.etat }}</td>
                    <td><a href="{{ path('commande_show', {'id': commande.id}) }}"><i class="fa fa-book"></i></a></td>
                </tr>
            {% endfor %}
        </table>
    </div>

    <a href="{{ path('membre_index') }}">back to list</a>

    <a href="{{ path('membre_edit', {'id': membre.id}) }}">edit</a>

    {{ include('membre/_delete_form.html.twig') }}
{% endblock %}